### ISSUE TITLE
"Days until I can post F3lixsram's personal info to Doxbin:"

### ISSUE THREAD

**Issue by S-PScripts** [ImmediateMurderProfessionals/ImmediateMurderProfessionals#2]
the hell does that mean??
how would you even know that???

and what is the purpose??

**Comment by ImmediateMurderProfessionals** [comment]
> the hell does that mean?? how would you even know that???
> 
> and what is the purpose??

f3lixsram is a gd creator
i know their personal info
i posted their doxx to gd but i can't post it to doxbin until they turn 15, which is on 12/9/2024

**Comment by S-PScripts** [comment]
> > the hell does that mean?? how would you even know that???
> > and what is the purpose??
> 
> f3lixsram is a gd creator i know their personal info i posted their doxx to gd but i can't post it to doxbin until they turn 15, which is on 12/9/2024

first of all how did you find their personal info and second of all why dox it????????????????????????

**Comment by S-PScripts** [comment]
bro is really doxxing now

**Comment by ImmediateMurderProfessionals** [comment]
> > > the hell does that mean?? how would you even know that???
> > > and what is the purpose??
> > 
> > 
> > f3lixsram is a gd creator i know their personal info i posted their doxx to gd but i can't post it to doxbin until they turn 15, which is on 12/9/2024
> 
> first of all how did you find their personal info and second of all why dox it????????????????????????

I'll tell you a secret: All the personal info is fake

**Comment by S-PScripts** [comment]
sex
